In [1]:
# Q1

import numpy as np

friend1 = np.array([7000,8000,9000,7500,8500,9500,10000])
friend2 = np.array([6500,8200,8800,7000,9000,9200,9800])

friend1 + friend2

friend1 - friend2

friend1 * friend2

friend1 / friend2

array([1.07692308, 0.97560976, 1.02272727, 1.07142857, 0.94444444,
       1.0326087 , 1.02040816])

In [2]:
# Q2

import numpy as np

user_pref = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

song_pop = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

np.dot(user_pref, song_pop)

np.matmul(user_pref, song_pop)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [3]:
# Q3

import numpy as np

img = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]
])

img.T

np.mean(img)

np.median(img)

np.std(img)

np.var(img)

np.float64(2125.0)

In [4]:
# Q4

import numpy as np

a = np.array([
    [4,2,1],
    [2,5,3],
    [1,3,6]
])

np.linalg.inv(a)

np.linalg.det(a)

np.linalg.eig(a)

EigResult(eigenvalues=array([9.34849393, 3.73015912, 1.92134694]), eigenvectors=array([[-0.3650547 , -0.77587586,  0.5145403 ],
       [-0.63657455, -0.19527095, -0.74608451],
       [-0.67934373,  0.59990492,  0.42261825]]))

In [5]:
# Q5

import numpy as np

orders = np.array([
    [100,120,140,160,180,200],
    [90,110,130,150,170,190]
])

orders.reshape(3,4)

orders.flatten()

a,b = np.split(orders.flatten(),2)

np.vstack((a,b))

array([[100, 120, 140, 160, 180, 200],
       [ 90, 110, 130, 150, 170, 190]])