In [1]:
# Q1
import numpy as np

ratings = np.array([
    [4, 5, 3, 4, 5],
    [5, 4, 4, 3, 5],
    [3, 4, 5, 4, 4],
    [5, 5, 4, 5, 3]
])

ratings[1:3]


array([[5, 4, 4, 3, 5],
       [3, 4, 5, 4, 4]])

In [2]:
# Q2

import numpy as np

steps = np.array([7500, 8200, 9000, 6500, 10000, 7800, 8500, 9200, 7000, 8800])

steps[steps > 8000]

array([ 8200,  9000, 10000,  8500,  9200,  8800])

In [3]:
# Q3

import numpy as np

scores = np.array([180, 195, 210, 175, 220, 190, 205, 198])

scores[[1, 4, 6]]

array([195, 220, 205])

In [4]:
# Q4

import numpy as np

prices = np.array([500, 1200, 800, 1500, 2000])

prices * 0.9

array([ 450., 1080.,  720., 1350., 1800.])

In [5]:
# Q5

import numpy as np

ratings = np.array([5, -2, 3, -1, 0, 4, -3])

ratings[ratings < 0] = 0

ratings

array([5, 0, 3, 0, 0, 4, 0])