In [ ]:
# Q1
import numpy as np

In [ ]:
# Q2
import numpy as np

followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Followers :", followers)
print("Shape :", followers.shape)
print("Dimensions :", followers.ndim)
print("Data Type :", followers.dtype)

Followers : [   1200   15000   67000  340000 1250000]
Shape : (5,)
Dimensions : 1
Data Type : int64


In [ ]:
# Q3
import numpy as np

order_ids = np.arange(101, 111)

print("Order IDs :", order_ids)
print("Size :", order_ids.size)

Order IDs : [101 102 103 104 105 106 107 108 109 110]
Size : 10


In [2]:
# Q4

import numpy as np

likes = np.eye(3)

print(likes)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# Q3
import numpy as np

scores = [45, 67, 120, 89, 54]

arr = np.array(scores)

print("Scores :", arr)
print("Item Size :", arr.itemsize, "bytes")

Scores : [ 45  67 120  89  54]
Item Size : 8 bytes
